name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm
    name: "Build with devkitARM"
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup NodejS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependency
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install ffmpeg build-essential -y

          npm -g install ytdl
      
      - name: Prepare video
        run: |
          cd assets
          ytdl "https://www.youtube.com/watch?v=dQw4w9WgXcQ" -o video.mp4

          sh convert.sh

      - name: Encode video
        run: |
          cd encoder
          npm install

          cd cpp
          g++ lzss.cpp -o lzss
          cd ..

          node .
        
      - name: Build NDS
        run: |
          cp assets/music.raw NDS/nitrofiles/
          cp encoder/data_compress NDS/nitrofiles/

          cd NDS
          make

      - name: Prepare artefact
        run: |
          cd NDS/dist
          mkdir -p dist
          tar -czvf dist/${{ github.event.repository.name }}.tar.gz *.nds

      - name: Upload to basement
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./NDS/dist/dist/
          server-dir: ./public_html/basement/${{ github.event.repository.name }}/